/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/trainings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTrainingById"];
        put: operations["updateTraining"];
        post?: never;
        delete: operations["deleteTraining"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSessionById"];
        put: operations["updateSession"];
        post?: never;
        delete: operations["deleteSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/programs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a training program by ID */
        get: operations["getProgramById"];
        /** Update an existing training program */
        put: operations["updateProgram"];
        post?: never;
        /** Delete a training program by ID */
        delete: operations["deleteProgram"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercises/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getExerciseById"];
        put: operations["updateExercise"];
        post?: never;
        delete: operations["deleteExercise"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trainings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAllTrainings"];
        put?: never;
        post: operations["createTraining"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trainings/{id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["startTraining"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trainings/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["completeTraining"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trainings/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancelTraining"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trainings/from-session/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createTrainingFromSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAllSessions"];
        put?: never;
        post: operations["createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/programs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all training programs */
        get: operations["getAllPrograms"];
        put?: never;
        /** Create a new training program */
        post: operations["createProgram"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/programs/{id}/generate-schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate scheduled calendar workouts across the program duration */
        post: operations["generateSchedule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAllExercises"];
        put?: never;
        post: operations["createExercise"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trainings/{id}/exists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["trainingExists"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stretch-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAllStretchTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stretch-types/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getStretchTypeByName"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{id}/exists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["sessionExists"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/programs/{id}/exists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check if a training program exists by ID */
        get: operations["programExists"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/muscle-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAllMuscleGroups"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/muscle-groups/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMuscleGroupByName"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/movement-patterns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAllMovementPatterns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/movement-patterns/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMovementPatternByName"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mobility-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAllMobilityTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mobility-types/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMobilityTypeByName"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/joints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAllJoints"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/joints/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getJointByName"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercises/{id}/exists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["exerciseExists"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/equipment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAllEquipment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/equipment/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getEquipmentByName"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/endurance-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAllEnduranceTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/endurance-types/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getEnduranceTypeByName"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/personal-records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get personal records across all exercises from completed workouts */
        get: operations["getPersonalRecords"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/personal-records/exercise/{exerciseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get personal records for a specific exercise from completed workouts */
        get: operations["getPersonalRecordsByExercise"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/muscle-volume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get weekly muscle group volume and hypertrophy balance analysis */
        get: operations["getMuscleVolume"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/acwr": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Calculate Acute:Chronic Workload Ratio (ACWR) and fatigue status */
        get: operations["calculateAcwr"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/1rm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Calculate estimated 1RM and percentage load breakdown */
        get: operations["calculate1Rm"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Distance: {
            /** Format: double */
            value?: number;
            /** @enum {string} */
            unit?: "METERS" | "KILOMETERS" | "MILES";
        };
        Duration: {
            /** Format: int32 */
            totalSeconds?: number;
        };
        EnduranceInterval: {
            /** Format: int32 */
            intervalNumber?: number;
            distance?: components["schemas"]["Distance"];
            duration?: components["schemas"]["Duration"];
            pace?: components["schemas"]["Pace"];
            /** Format: int32 */
            avgHeartRate?: number;
            /** Format: int32 */
            maxHeartRate?: number;
            /** Format: double */
            avgPower?: number;
            /** Format: double */
            cadence?: number;
            /** Format: int32 */
            restSeconds?: number;
        };
        EnduranceMetrics: {
            /** Format: int32 */
            id?: number;
            /** @enum {string} */
            enduranceType?: "AEROBIC" | "ANAEROBIC" | "HIIT" | "SIT" | "LISS" | "TEMPO" | "FARTLEK" | "STEADY_STATE";
            /** Format: int32 */
            blocks?: number;
            /** Format: int32 */
            repetitions?: number;
            /** Format: int32 */
            restBetweenBlocks?: number;
            /** Format: int32 */
            restBetweenRepetitions?: number;
            /** Format: double */
            trackDistance?: number;
            /** Format: int32 */
            trackDuration?: number;
            /** Format: int32 */
            trackPace?: number;
            /** Format: int32 */
            trackAverageHeartRate?: number;
            /** Format: int32 */
            trackMinHeartRate?: number;
            /** Format: int32 */
            trackMaxHeartRate?: number;
            /** Format: int32 */
            trackTargetHeartRate?: number;
            /** Format: int32 */
            trackAveragePace?: number;
            /** Format: int32 */
            trackMinPace?: number;
            /** Format: int32 */
            trackMaxPace?: number;
            /** Format: int32 */
            trackTargetPace?: number;
            /** Format: double */
            trackAveragePower?: number;
            /** Format: double */
            trackMinPower?: number;
            /** Format: double */
            trackMaxPower?: number;
            /** Format: double */
            trackTargetPower?: number;
            /** Format: double */
            trackAverageCadence?: number;
            /** Format: double */
            trackMinCadence?: number;
            /** Format: double */
            trackMaxCadence?: number;
            /** Format: double */
            trackTargetCadence?: number;
            /** Format: double */
            trackAverageSpeed?: number;
            /** Format: double */
            trackMinSpeed?: number;
            /** Format: double */
            trackMaxSpeed?: number;
            /** Format: double */
            trackTargetSpeed?: number;
            /** Format: double */
            restTrackDistance?: number;
            /** Format: int32 */
            restTrackDuration?: number;
            /** Format: int32 */
            restTrackPace?: number;
            /** Format: int32 */
            restTrackAverageHeartRate?: number;
            /** Format: int32 */
            restTrackMinHeartRate?: number;
            /** Format: int32 */
            restTrackMaxHeartRate?: number;
            /** Format: int32 */
            restTrackTargetHeartRate?: number;
            /** Format: double */
            restTrackAveragePower?: number;
            /** Format: double */
            restTrackMinPower?: number;
            /** Format: double */
            restTrackMaxPower?: number;
            /** Format: double */
            restTrackTargetPower?: number;
            /** Format: double */
            restTrackAverageCadence?: number;
            /** Format: double */
            restTrackMinCadence?: number;
            /** Format: double */
            restTrackMaxCadence?: number;
            /** Format: double */
            restTrackTargetCadence?: number;
            /** Format: double */
            restTrackAverageSpeed?: number;
            /** Format: double */
            restTrackMinSpeed?: number;
            /** Format: double */
            restTrackMaxSpeed?: number;
            /** Format: double */
            restTrackTargetSpeed?: number;
            distanceUnit?: string;
            paceUnit?: string;
            heartRateUnit?: string;
            powerUnit?: string;
            /** Format: int32 */
            recommendedBlocks?: number;
            /** Format: int32 */
            recommendedRepetitions?: number;
            /** Format: int32 */
            recommendedRestBetweenBlocks?: number;
            /** Format: int32 */
            recommendedRestBetweenRepetitions?: number;
            /** Format: double */
            recommendedTrackDistance?: number;
            /** Format: int32 */
            recommendedTrackDuration?: number;
            /** Format: int32 */
            recommendedTrackPace?: number;
            /** Format: int32 */
            recommendedTrackAverageHeartRate?: number;
            /** Format: int32 */
            recommendedTrackMinHeartRate?: number;
            /** Format: int32 */
            recommendedTrackMaxHeartRate?: number;
            /** Format: int32 */
            recommendedTrackTargetHeartRate?: number;
            /** Format: double */
            recommendedTrackAveragePower?: number;
            /** Format: double */
            recommendedTrackMinPower?: number;
            /** Format: double */
            recommendedTrackMaxPower?: number;
            /** Format: double */
            recommendedTrackTargetPower?: number;
            /** Format: double */
            recommendedTrackAverageCadence?: number;
            /** Format: double */
            recommendedTrackMinCadence?: number;
            /** Format: double */
            recommendedTrackMaxCadence?: number;
            /** Format: double */
            recommendedTrackTargetCadence?: number;
            /** Format: double */
            recommendedTrackAverageSpeed?: number;
            /** Format: double */
            recommendedTrackMinSpeed?: number;
            /** Format: double */
            recommendedTrackMaxSpeed?: number;
            /** Format: double */
            recommendedTrackTargetSpeed?: number;
            /** Format: double */
            recommendedRestTrackDistance?: number;
            /** Format: int32 */
            recommendedRestTrackDuration?: number;
            /** Format: int32 */
            recommendedRestTrackPace?: number;
            /** Format: int32 */
            recommendedRestTrackAverageHeartRate?: number;
            /** Format: int32 */
            recommendedRestTrackMinHeartRate?: number;
            /** Format: int32 */
            recommendedRestTrackMaxHeartRate?: number;
            /** Format: int32 */
            recommendedRestTrackTargetHeartRate?: number;
            /** Format: double */
            recommendedRestTrackAveragePower?: number;
            /** Format: double */
            recommendedRestTrackMinPower?: number;
            /** Format: double */
            recommendedRestTrackMaxPower?: number;
            /** Format: double */
            recommendedRestTrackTargetPower?: number;
            /** Format: double */
            recommendedRestTrackAverageCadence?: number;
            /** Format: double */
            recommendedRestTrackMinCadence?: number;
            /** Format: double */
            recommendedRestTrackMaxCadence?: number;
            /** Format: double */
            recommendedRestTrackTargetCadence?: number;
            /** Format: double */
            recommendedRestTrackAverageSpeed?: number;
            /** Format: double */
            recommendedRestTrackMinSpeed?: number;
            /** Format: double */
            recommendedRestTrackMaxSpeed?: number;
            /** Format: double */
            recommendedRestTrackTargetSpeed?: number;
        };
        EnduranceSessionExercise: {
            exerciseType: "EnduranceSessionExercise";
        } & (Omit<components["schemas"]["SessionExercise"], "exerciseType"> & {
            intervals?: components["schemas"]["EnduranceInterval"][];
        });
        Exercise: {
            /** Format: int32 */
            id?: number;
            name?: string;
            description?: string;
            images?: string[];
            video?: string;
            /** @enum {string} */
            primaryCategory?: "RESISTANCE" | "ENDURANCE" | "MOBILITY" | "FUNCTIONAL" | "PLYOMETRICS" | "BALANCE" | "CORE" | "CALISTHENICS" | "NEUROMUSCULAR" | "POWER" | "STABILIZATION" | "AGILITY" | "SPEED" | "PILATES" | "ISOMETRIC" | "CIRCUIT" | "REHABILITATION" | "SPORT_SPECIFIC";
            secondaryCategories?: ("RESISTANCE" | "ENDURANCE" | "MOBILITY" | "FUNCTIONAL" | "PLYOMETRICS" | "BALANCE" | "CORE" | "CALISTHENICS" | "NEUROMUSCULAR" | "POWER" | "STABILIZATION" | "AGILITY" | "SPEED" | "PILATES" | "ISOMETRIC" | "CIRCUIT" | "REHABILITATION" | "SPORT_SPECIFIC")[];
            resistanceMetrics?: components["schemas"]["ResistanceMetrics"];
            enduranceMetrics?: components["schemas"]["EnduranceMetrics"];
            mobilityMetrics?: components["schemas"]["MobilityMetrics"];
            equipmentRequired?: ("BODYWEIGHT" | "BARBELL" | "DUMBBELL" | "KETTLEBELL" | "WEIGHT_PLATE" | "EZ_BAR" | "TRAP_BAR" | "RESISTANCE_BAND" | "CABLE_MACHINE" | "SUSPENSION_TRAINER" | "SMITH_MACHINE" | "CHEST_PRESS" | "INCLINE_CHEST_PRESS" | "DECLINE_CHEST_PRESS" | "CHEST_FLY" | "CABLE_CROSSOVER" | "LAT_PULLDOWN" | "SEATED_CABLE_ROW" | "SEATED_ROW" | "T_BAR_ROW" | "BACK_EXTENSION" | "ASSISTED_PULL_UP" | "SHOULDER_PRESS" | "LATERAL_RAISE" | "REAR_DELT_FLY" | "SHRUG_MACHINE" | "BICEP_CURL" | "PREACHER_CURL" | "TRICEP_EXTENSION" | "TRICEP_PRESSDOWN" | "TRICEP_DIP" | "LEG_PRESS" | "HACK_SQUAT" | "LEG_EXTENSION" | "LEG_CURL" | "SEATED_LEG_CURL" | "LYING_LEG_CURL" | "HIP_ABDUCTOR" | "HIP_ADDUCTOR" | "GLUTE_KICKBACK" | "PENDULUM_SQUAT" | "STANDING_CALF_RAISE" | "SEATED_CALF_RAISE" | "LEG_PRESS_CALF_RAISE" | "AB_CRUNCH_MACHINE" | "TORSO_ROTATION" | "CAPTAIN_CHAIR" | "TREADMILL" | "STATIONARY_BIKE" | "ROWING_MACHINE" | "ELLIPTICAL" | "STAIR_CLIMBER" | "ASSAULT_BIKE" | "SKI_MACHINE" | "PULL_UP_BAR" | "DIP_STATION" | "BENCH" | "POWER_RACK" | "PLYO_BOX" | "TRX" | "MEDICINE_BALL" | "SLAM_BALL" | "FOAM_ROLLER" | "YOGA_MAT" | "AB_WHEEL" | "BATTLE_ROPE")[];
            /** @enum {string} */
            difficultyLevel?: "BEGINNER" | "INTERMEDIATE" | "ADVANCED" | "EXPERT";
            stepByStepInstructions?: string[];
            commonMistakes?: string[];
            safetyTips?: string[];
            alternativeExercises?: string[];
            createdBy?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            tags?: string[];
            active?: boolean;
        };
        MobilityMetrics: {
            /** Format: int32 */
            id?: number;
            /** @enum {string} */
            mobilityType?: "STATIC_STRETCHING" | "DYNAMIC_MOBILITY" | "FOAM_ROLLING" | "YOGA" | "PNF_STRETCHING" | "ACTIVE_STRETCHING" | "MOBILITY_DRILLS";
            /** @enum {string} */
            stretchType?: "STATIC" | "DYNAMIC" | "PNF" | "BALLISTIC" | "ACTIVE" | "PASSIVE";
            targetJoints?: ("NECK" | "SHOULDER" | "ELBOW" | "WRIST" | "THORACIC_SPINE" | "LUMBAR_SPINE" | "HIP" | "KNEE" | "ANKLE" | "FULL_BODY")[];
            romMeasurementMethod?: string;
            /** Format: int32 */
            recommendedHoldTimeSeconds?: number;
            /** Format: int32 */
            recommendedRepetitions?: number;
            /** Format: int32 */
            recommendedSets?: number;
            performBilaterally?: boolean;
            /** @enum {string} */
            timing?: "PRE_WORKOUT" | "POST_WORKOUT" | "STANDALONE" | "DAILY" | "ACTIVE_RECOVERY";
        };
        MobilitySessionExercise: {
            exerciseType: "MobilitySessionExercise";
        } & (Omit<components["schemas"]["SessionExercise"], "exerciseType"> & {
            sets?: components["schemas"]["MobilitySet"][];
        });
        MobilitySet: {
            /** Format: int32 */
            setNumber?: number;
            holdDuration?: components["schemas"]["Duration"];
            /** Format: int32 */
            repetitions?: number;
            bilateral?: boolean;
        };
        Pace: {
            /** Format: int32 */
            secondsPerUnit?: number;
            /** @enum {string} */
            unit?: "METERS" | "KILOMETERS" | "MILES";
        };
        ResistanceMetrics: {
            /** Format: int32 */
            id?: number;
            primaryMuscles?: ("CHEST" | "UPPER_BACK" | "LATS" | "LOWER_BACK" | "SHOULDERS" | "BICEPS" | "TRICEPS" | "FOREARMS" | "ABS" | "OBLIQUES" | "CORE" | "QUADRICEPS" | "HAMSTRINGS" | "GLUTES" | "CALVES" | "HIP_FLEXORS" | "ADDUCTORS" | "FULL_BODY")[];
            secondaryMuscles?: ("CHEST" | "UPPER_BACK" | "LATS" | "LOWER_BACK" | "SHOULDERS" | "BICEPS" | "TRICEPS" | "FOREARMS" | "ABS" | "OBLIQUES" | "CORE" | "QUADRICEPS" | "HAMSTRINGS" | "GLUTES" | "CALVES" | "HIP_FLEXORS" | "ADDUCTORS" | "FULL_BODY")[];
            /** @enum {string} */
            movementPattern?: "PUSH" | "PULL" | "SQUAT" | "HINGE" | "LUNGE" | "CARRY" | "ROTATION" | "ISOLATION" | "COMPOUND";
            defaultWeightUnit?: string;
            /** Format: int32 */
            recommendedSets?: number;
            /** Format: int32 */
            recommendedRepsMin?: number;
            /** Format: int32 */
            recommendedRepsMax?: number;
            /** Format: int32 */
            recommendedRestSeconds?: number;
            tempoRecommendation?: string;
            /** Format: double */
            minWeight?: number;
            /** Format: double */
            maxWeight?: number;
            /** Format: double */
            weightIncrement?: number;
            weighted?: boolean;
            bodyweight?: boolean;
            timed?: boolean;
        };
        ResistanceSessionExercise: {
            exerciseType: "ResistanceSessionExercise";
        } & (Omit<components["schemas"]["SessionExercise"], "exerciseType"> & {
            sets?: components["schemas"]["ResistanceSet"][];
        });
        ResistanceSet: {
            /** Format: int32 */
            setNumber?: number;
            /** @enum {string} */
            setType?: "WARMUP" | "WORKING" | "DROP_SET" | "MYOREP" | "FAILURE";
            weight?: components["schemas"]["Weight"];
            /** Format: int32 */
            repetitions?: number;
            rpe?: components["schemas"]["Rpe"];
            /** Format: int32 */
            restSeconds?: number;
        };
        Rpe: {
            /** Format: double */
            value?: number;
        };
        SessionExercise: {
            /** Format: int32 */
            id?: number;
            exercise?: components["schemas"]["Exercise"];
            /** Format: int32 */
            orderIndex?: number;
            notes?: string;
            exerciseType: string;
        };
        SessionRequest: {
            /** Format: int32 */
            id?: number;
            name: string;
            description?: string;
            /** @enum {string} */
            sessionStatus?: "Planned" | "Draft" | "Ready to Start" | "In Progress" | "Paused" | "Completed" | "Partially Completed" | "Skipped" | "Missed" | "Cancelled" | "Failed/Abandoned";
            sessionExercises?: (components["schemas"]["EnduranceSessionExercise"] | components["schemas"]["MobilitySessionExercise"] | components["schemas"]["ResistanceSessionExercise"])[];
            /** Format: date-time */
            startTime?: string;
            /** Format: date-time */
            endTime?: string;
            notes?: string;
            rpe?: components["schemas"]["Rpe"];
        };
        TrainingRequest: {
            /** Format: int32 */
            id?: number;
            name: string;
            description?: string;
            session: components["schemas"]["SessionRequest"];
            /** Format: date */
            trainingDate: string;
            /** Format: date-time */
            startTime?: string;
            /** Format: date-time */
            endTime?: string;
            /** @enum {string} */
            status?: "Planned" | "In Progress" | "Paused" | "Completed" | "Partially Completed" | "Skipped" | "Cancelled";
            notes?: string;
            rpe?: components["schemas"]["Rpe"];
        };
        Weight: {
            /** Format: double */
            value?: number;
            /** @enum {string} */
            unit?: "KG" | "LBS";
        };
        Session: {
            /** Format: int32 */
            id?: number;
            name?: string;
            description?: string;
            /** @enum {string} */
            sessionStatus?: "Planned" | "Draft" | "Ready to Start" | "In Progress" | "Paused" | "Completed" | "Partially Completed" | "Skipped" | "Missed" | "Cancelled" | "Failed/Abandoned";
            sessionExercises?: (components["schemas"]["EnduranceSessionExercise"] | components["schemas"]["MobilitySessionExercise"] | components["schemas"]["ResistanceSessionExercise"])[];
            /** Format: date-time */
            startTime?: string;
            /** Format: date-time */
            endTime?: string;
            notes?: string;
            rpe?: components["schemas"]["Rpe"];
            duration?: components["schemas"]["Duration"];
            /** Format: double */
            totalVolume?: number;
        };
        Training: {
            /** Format: int32 */
            id?: number;
            name?: string;
            description?: string;
            session?: components["schemas"]["Session"];
            /** Format: date */
            trainingDate?: string;
            /** Format: date-time */
            startTime?: string;
            /** Format: date-time */
            endTime?: string;
            duration?: components["schemas"]["Duration"];
            /** Format: double */
            totalVolume?: number;
            /** @enum {string} */
            status?: "Planned" | "In Progress" | "Paused" | "Completed" | "Partially Completed" | "Skipped" | "Cancelled";
            notes?: string;
            rpe?: components["schemas"]["Rpe"];
        };
        /** @description Scheduled workout day within a program microcycle */
        ProgramWorkoutRequest: {
            /**
             * Format: int32
             * @description Day of week (1 = Monday, 7 = Sunday)
             * @example 1
             */
            dayOfWeek: number;
            /**
             * @description Training focus or target muscle groups
             * @example Upper Body Strength
             */
            focus?: string;
            /** @description Session template executed on this day */
            session: components["schemas"]["SessionRequest"];
        };
        TrainingProgramRequest: {
            /** Format: int32 */
            id?: number;
            /**
             * @description Program title
             * @example 12-Week Push Pull Legs
             */
            name: string;
            /** @description Program description and training objectives */
            description?: string;
            /**
             * Format: int32
             * @description Program duration in weeks
             * @example 12
             */
            durationWeeks?: number;
            /**
             * @description Periodization methodology
             * @example LINEAR
             * @enum {string}
             */
            periodizationType?: "LINEAR" | "BLOCK" | "UNDULATING" | "REVERSE_LINEAR";
            /**
             * @description Target athlete experience level
             * @example INTERMEDIATE
             * @enum {string}
             */
            level?: "BEGINNER" | "INTERMEDIATE" | "ADVANCED" | "ELITE";
            /** @description List of scheduled workout days in a microcycle */
            workouts?: components["schemas"]["ProgramWorkoutRequest"][];
            /**
             * @description Whether the program is active and available
             * @example true
             */
            isActive?: boolean;
        };
        ProgramWorkoutResponse: {
            /**
             * Format: int32
             * @description Day of week (1 = Monday, 7 = Sunday)
             * @example 1
             */
            dayOfWeek?: number;
            /**
             * @description Training focus or target muscle groups
             * @example Upper Body Strength
             */
            focus?: string;
            /** @description Session template executed on this day */
            session?: components["schemas"]["Session"];
        };
        TrainingProgramResponse: {
            /** Format: int32 */
            id?: number;
            name?: string;
            description?: string;
            /** Format: int32 */
            durationWeeks?: number;
            /** @enum {string} */
            periodizationType?: "LINEAR" | "BLOCK" | "UNDULATING" | "REVERSE_LINEAR";
            /** @enum {string} */
            level?: "BEGINNER" | "INTERMEDIATE" | "ADVANCED" | "ELITE";
            workouts?: components["schemas"]["ProgramWorkoutResponse"][];
            isActive?: boolean;
        };
        ExerciseRequest: {
            /** Format: int32 */
            id?: number;
            name: string;
            description?: string;
            images?: string[];
            video?: string;
            /** @enum {string} */
            primaryCategory: "RESISTANCE" | "ENDURANCE" | "MOBILITY" | "FUNCTIONAL" | "PLYOMETRICS" | "BALANCE" | "CORE" | "CALISTHENICS" | "NEUROMUSCULAR" | "POWER" | "STABILIZATION" | "AGILITY" | "SPEED" | "PILATES" | "ISOMETRIC" | "CIRCUIT" | "REHABILITATION" | "SPORT_SPECIFIC";
            secondaryCategories?: ("RESISTANCE" | "ENDURANCE" | "MOBILITY" | "FUNCTIONAL" | "PLYOMETRICS" | "BALANCE" | "CORE" | "CALISTHENICS" | "NEUROMUSCULAR" | "POWER" | "STABILIZATION" | "AGILITY" | "SPEED" | "PILATES" | "ISOMETRIC" | "CIRCUIT" | "REHABILITATION" | "SPORT_SPECIFIC")[];
            resistanceMetrics?: components["schemas"]["ResistanceMetrics"];
            enduranceMetrics?: components["schemas"]["EnduranceMetrics"];
            mobilityMetrics?: components["schemas"]["MobilityMetrics"];
            equipmentRequired?: ("BODYWEIGHT" | "BARBELL" | "DUMBBELL" | "KETTLEBELL" | "WEIGHT_PLATE" | "EZ_BAR" | "TRAP_BAR" | "RESISTANCE_BAND" | "CABLE_MACHINE" | "SUSPENSION_TRAINER" | "SMITH_MACHINE" | "CHEST_PRESS" | "INCLINE_CHEST_PRESS" | "DECLINE_CHEST_PRESS" | "CHEST_FLY" | "CABLE_CROSSOVER" | "LAT_PULLDOWN" | "SEATED_CABLE_ROW" | "SEATED_ROW" | "T_BAR_ROW" | "BACK_EXTENSION" | "ASSISTED_PULL_UP" | "SHOULDER_PRESS" | "LATERAL_RAISE" | "REAR_DELT_FLY" | "SHRUG_MACHINE" | "BICEP_CURL" | "PREACHER_CURL" | "TRICEP_EXTENSION" | "TRICEP_PRESSDOWN" | "TRICEP_DIP" | "LEG_PRESS" | "HACK_SQUAT" | "LEG_EXTENSION" | "LEG_CURL" | "SEATED_LEG_CURL" | "LYING_LEG_CURL" | "HIP_ABDUCTOR" | "HIP_ADDUCTOR" | "GLUTE_KICKBACK" | "PENDULUM_SQUAT" | "STANDING_CALF_RAISE" | "SEATED_CALF_RAISE" | "LEG_PRESS_CALF_RAISE" | "AB_CRUNCH_MACHINE" | "TORSO_ROTATION" | "CAPTAIN_CHAIR" | "TREADMILL" | "STATIONARY_BIKE" | "ROWING_MACHINE" | "ELLIPTICAL" | "STAIR_CLIMBER" | "ASSAULT_BIKE" | "SKI_MACHINE" | "PULL_UP_BAR" | "DIP_STATION" | "BENCH" | "POWER_RACK" | "PLYO_BOX" | "TRX" | "MEDICINE_BALL" | "SLAM_BALL" | "FOAM_ROLLER" | "YOGA_MAT" | "AB_WHEEL" | "BATTLE_ROPE")[];
            /** @enum {string} */
            difficultyLevel?: "BEGINNER" | "INTERMEDIATE" | "ADVANCED" | "EXPERT";
            stepByStepInstructions?: string[];
            commonMistakes?: string[];
            safetyTips?: string[];
            alternativeExercises?: string[];
            tags?: string[];
        };
        BestEstimated1RmRecord: {
            /** Format: double */
            estimated1Rm?: number;
            /** @enum {string} */
            unit?: "KG" | "LBS";
            /** Format: double */
            sourceWeight?: number;
            /** Format: int32 */
            sourceReps?: number;
            /** @enum {string} */
            formula?: "EPLEY" | "BRZYCKI" | "LOMBARDI" | "MAYHEW" | "OCONNER" | "WATHEN";
            /** Format: int32 */
            trainingId?: number;
            /** Format: date */
            trainingDate?: string;
        };
        MaxRepsRecord: {
            /** Format: int32 */
            repetitions?: number;
            /** Format: double */
            weight?: number;
            /** @enum {string} */
            unit?: "KG" | "LBS";
            /** Format: int32 */
            trainingId?: number;
            /** Format: date */
            trainingDate?: string;
        };
        MaxSessionVolumeRecord: {
            /** Format: double */
            volume?: number;
            /** @enum {string} */
            unit?: "KG" | "LBS";
            /** Format: int32 */
            trainingId?: number;
            /** Format: date */
            trainingDate?: string;
        };
        MaxWeightRecord: {
            /** Format: double */
            value?: number;
            /** @enum {string} */
            unit?: "KG" | "LBS";
            /** Format: int32 */
            repetitions?: number;
            /** Format: int32 */
            trainingId?: number;
            /** Format: date */
            trainingDate?: string;
        };
        /** @description Personal records achieved for an exercise across completed workouts */
        PersonalRecordResponse: {
            /**
             * Format: int32
             * @description Exercise ID
             * @example 1
             */
            exerciseId?: number;
            /**
             * @description Exercise name
             * @example Bench Press
             */
            exerciseName?: string;
            /** @description Maximum weight record */
            maxWeight?: components["schemas"]["MaxWeightRecord"];
            /** @description Best estimated 1RM record */
            bestEstimated1Rm?: components["schemas"]["BestEstimated1RmRecord"];
            /** @description Maximum session volume record */
            maxSessionVolume?: components["schemas"]["MaxSessionVolumeRecord"];
            /** @description Maximum repetitions record */
            maxReps?: components["schemas"]["MaxRepsRecord"];
        };
        /** @description Aggregated working volume for an individual muscle group */
        MuscleGroupVolume: {
            /**
             * @description Muscle group identifier
             * @example CHEST
             * @enum {string}
             */
            muscleGroup?: "CHEST" | "UPPER_BACK" | "LATS" | "LOWER_BACK" | "SHOULDERS" | "BICEPS" | "TRICEPS" | "FOREARMS" | "ABS" | "OBLIQUES" | "CORE" | "QUADRICEPS" | "HAMSTRINGS" | "GLUTES" | "CALVES" | "HIP_FLEXORS" | "ADDUCTORS" | "FULL_BODY";
            /**
             * @description Human-readable muscle group name
             * @example Chest
             */
            muscleGroupName?: string;
            /**
             * @description Anatomical category
             * @example UPPER_BODY
             * @enum {string}
             */
            category?: "UPPER_BODY" | "CORE" | "LOWER_BODY" | "FULL_BODY";
            /**
             * Format: int32
             * @description Number of primary/direct working sets
             * @example 12
             */
            directSets?: number;
            /**
             * Format: int32
             * @description Number of secondary/indirect synergist sets
             * @example 6
             */
            indirectSets?: number;
            /**
             * Format: double
             * @description Effective working sets (direct + 0.5 * indirect)
             * @example 15
             */
            effectiveSets?: number;
            /**
             * Format: double
             * @description Total tonnage moved in kilograms
             * @example 8400
             */
            totalVolumeKg?: number;
            /**
             * @description Hypertrophy landmark classification
             * @example OPTIMAL
             * @enum {string}
             */
            status?: "UNDERTRAINED" | "MAINTENANCE" | "OPTIMAL" | "OVERTRAINED";
            /**
             * @description Human-readable status label
             * @example Optimal Hypertrophy
             */
            statusDisplayName?: string;
            /** @description Evidence-based guideline for this volume level */
            statusDescription?: string;
        };
        /** @description Weekly muscle group working volume and hypertrophy balance analysis */
        WeeklyMuscleVolumeResponse: {
            /**
             * Format: date
             * @description Start date of the evaluation window
             * @example 2026-09-15
             */
            startDate?: string;
            /**
             * Format: date
             * @description End date of the evaluation window
             * @example 2026-09-21
             */
            endDate?: string;
            /**
             * Format: int32
             * @description Total completed working sets across all exercises
             * @example 48
             */
            totalWorkingSets?: number;
            /**
             * Format: double
             * @description Total tonnage moved in kilograms
             * @example 32500
             */
            totalVolumeKg?: number;
            /** @description Volume breakdown per muscle group, ordered by effective sets descending */
            muscleVolumes?: components["schemas"]["MuscleGroupVolume"][];
            /** @description Effective sets aggregated by anatomical category (UPPER_BODY, LOWER_BODY, etc.) */
            categoryVolumes?: {
                [key: string]: number;
            };
            /**
             * Format: double
             * @description Ratio of pushing sets to pulling sets
             * @example 1.1
             */
            pushPullRatio?: number;
            /**
             * Format: double
             * @description Ratio of upper body sets to lower body sets
             * @example 1.45
             */
            upperLowerRatio?: number;
            /** @description Major muscle groups with insufficient volume (< 6 sets) */
            neglectedMuscleGroups?: ("CHEST" | "UPPER_BACK" | "LATS" | "LOWER_BACK" | "SHOULDERS" | "BICEPS" | "TRICEPS" | "FOREARMS" | "ABS" | "OBLIQUES" | "CORE" | "QUADRICEPS" | "HAMSTRINGS" | "GLUTES" | "CALVES" | "HIP_FLEXORS" | "ADDUCTORS" | "FULL_BODY")[];
            /** @description Muscle groups within the optimal hypertrophy zone (10-20 sets) */
            optimalMuscleGroups?: ("CHEST" | "UPPER_BACK" | "LATS" | "LOWER_BACK" | "SHOULDERS" | "BICEPS" | "TRICEPS" | "FOREARMS" | "ABS" | "OBLIQUES" | "CORE" | "QUADRICEPS" | "HAMSTRINGS" | "GLUTES" | "CALVES" | "HIP_FLEXORS" | "ADDUCTORS" | "FULL_BODY")[];
            /** @description Muscle groups exceeding maximum recoverable volume (> 20 sets) */
            overtrainedMuscleGroups?: ("CHEST" | "UPPER_BACK" | "LATS" | "LOWER_BACK" | "SHOULDERS" | "BICEPS" | "TRICEPS" | "FOREARMS" | "ABS" | "OBLIQUES" | "CORE" | "QUADRICEPS" | "HAMSTRINGS" | "GLUTES" | "CALVES" | "HIP_FLEXORS" | "ADDUCTORS" | "FULL_BODY")[];
            /** @description Actionable evidence-based coaching recommendations */
            recommendations?: string[];
        };
        /** @description Acute:Chronic Workload Ratio (ACWR) and fatigue status */
        AcwrResponse: {
            /**
             * Format: date
             * @description Reference evaluation date
             * @example 2026-09-21
             */
            targetDate?: string;
            /**
             * Format: double
             * @description Acute workload (fatigue over the last 7 days) in AU
             * @example 1250
             */
            acuteWorkload?: number;
            /**
             * Format: double
             * @description Acute daily average load in AU/day
             * @example 178.57
             */
            acuteDailyAverage?: number;
            /**
             * Format: double
             * @description Chronic workload (accumulated over the last 28 days) in AU
             * @example 4200
             */
            chronicWorkload?: number;
            /**
             * Format: double
             * @description Chronic weekly average load in AU/week
             * @example 1050
             */
            chronicWeeklyAverage?: number;
            /**
             * Format: double
             * @description Chronic daily average load in AU/day
             * @example 150
             */
            chronicDailyAverage?: number;
            /**
             * Format: double
             * @description Acute to Chronic Workload Ratio (ACWR)
             * @example 1.19
             */
            acwr?: number;
            /**
             * @description Injury risk classification category
             * @example OPTIMAL
             * @enum {string}
             */
            riskZone?: "UNDERTRAINING" | "OPTIMAL" | "OVERREACHING" | "HIGH_RISK";
            /**
             * @description Human-readable label of the risk zone
             * @example Optimal Zone
             */
            riskZoneDisplayName?: string;
            /** @description Scientific explanation of the risk zone */
            statusDescription?: string;
            /**
             * @description Whether a deload week or active recovery is recommended
             * @example false
             */
            deloadRecommended?: boolean;
            /** @description Actionable sports science training and recovery advice */
            recommendation?: string;
            /** @description Chronological 28-day daily workload breakdown */
            dailyWorkloads?: components["schemas"]["DailyWorkloadResponse"][];
        };
        /** @description Workload metrics accumulated for a single day */
        DailyWorkloadResponse: {
            /**
             * Format: date
             * @description Calendar date
             * @example 2026-09-21
             */
            date?: string;
            /**
             * Format: double
             * @description Session RPE workload in arbitrary units (AU)
             * @example 360
             */
            workloadAu?: number;
            /**
             * Format: double
             * @description Total volume moved in kilograms
             * @example 4500
             */
            totalVolumeKg?: number;
            /**
             * Format: int32
             * @description Number of completed workouts on this day
             * @example 1
             */
            completedSessions?: number;
        };
        /** @description Estimated 1RM and percentage-based training loads */
        OneRepMaxResponse: {
            /**
             * Format: double
             * @description Input weight value
             * @example 100
             */
            weight?: number;
            /**
             * @description Input weight unit
             * @example KG
             * @enum {string}
             */
            unit?: "KG" | "LBS";
            /**
             * Format: int32
             * @description Input repetitions
             * @example 5
             */
            repetitions?: number;
            /**
             * @description Formula used for estimation
             * @example EPLEY
             * @enum {string}
             */
            formula?: "EPLEY" | "BRZYCKI" | "LOMBARDI" | "MAYHEW" | "OCONNER" | "WATHEN";
            /**
             * Format: double
             * @description Calculated 1RM estimate
             * @example 116.67
             */
            estimated1Rm?: number;
            /** @description Training loads by percentage of 1RM (50% to 95%) */
            percentages?: {
                [key: string]: number;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getTrainingById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Training"];
                };
            };
        };
    };
    updateTraining: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrainingRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Training"];
                };
            };
        };
    };
    deleteTraining: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getSessionById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Session"];
                };
            };
        };
    };
    updateSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Session"];
                };
            };
        };
    };
    deleteSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getProgramById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TrainingProgramResponse"];
                };
            };
        };
    };
    updateProgram: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrainingProgramRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TrainingProgramResponse"];
                };
            };
        };
    };
    deleteProgram: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getExerciseById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Exercise"];
                };
            };
        };
    };
    updateExercise: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExerciseRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Exercise"];
                };
            };
        };
    };
    deleteExercise: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getAllTrainings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Training"][];
                };
            };
        };
    };
    createTraining: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrainingRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Training"];
                };
            };
        };
    };
    startTraining: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Training"];
                };
            };
        };
    };
    completeTraining: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Training"];
                };
            };
        };
    };
    cancelTraining: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Training"];
                };
            };
        };
    };
    createTrainingFromSession: {
        parameters: {
            query?: {
                date?: string;
                customName?: string;
            };
            header?: never;
            path: {
                sessionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Training"];
                };
            };
        };
    };
    getAllSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Session"][];
                };
            };
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Session"];
                };
            };
        };
    };
    getAllPrograms: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TrainingProgramResponse"][];
                };
            };
        };
    };
    createProgram: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrainingProgramRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TrainingProgramResponse"];
                };
            };
        };
    };
    generateSchedule: {
        parameters: {
            query?: {
                startDate?: string;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Training"][];
                };
            };
        };
    };
    getAllExercises: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Exercise"][];
                };
            };
        };
    };
    createExercise: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExerciseRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Exercise"];
                };
            };
        };
    };
    trainingExists: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": boolean;
                };
            };
        };
    };
    getAllStretchTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": ("STATIC" | "DYNAMIC" | "PNF" | "BALLISTIC" | "ACTIVE" | "PASSIVE")[];
                };
            };
        };
    };
    getStretchTypeByName: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": "STATIC" | "DYNAMIC" | "PNF" | "BALLISTIC" | "ACTIVE" | "PASSIVE";
                };
            };
        };
    };
    sessionExists: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": boolean;
                };
            };
        };
    };
    programExists: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": boolean;
                };
            };
        };
    };
    getAllMuscleGroups: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": ("CHEST" | "UPPER_BACK" | "LATS" | "LOWER_BACK" | "SHOULDERS" | "BICEPS" | "TRICEPS" | "FOREARMS" | "ABS" | "OBLIQUES" | "CORE" | "QUADRICEPS" | "HAMSTRINGS" | "GLUTES" | "CALVES" | "HIP_FLEXORS" | "ADDUCTORS" | "FULL_BODY")[];
                };
            };
        };
    };
    getMuscleGroupByName: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": "CHEST" | "UPPER_BACK" | "LATS" | "LOWER_BACK" | "SHOULDERS" | "BICEPS" | "TRICEPS" | "FOREARMS" | "ABS" | "OBLIQUES" | "CORE" | "QUADRICEPS" | "HAMSTRINGS" | "GLUTES" | "CALVES" | "HIP_FLEXORS" | "ADDUCTORS" | "FULL_BODY";
                };
            };
        };
    };
    getAllMovementPatterns: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": ("PUSH" | "PULL" | "SQUAT" | "HINGE" | "LUNGE" | "CARRY" | "ROTATION" | "ISOLATION" | "COMPOUND")[];
                };
            };
        };
    };
    getMovementPatternByName: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": "PUSH" | "PULL" | "SQUAT" | "HINGE" | "LUNGE" | "CARRY" | "ROTATION" | "ISOLATION" | "COMPOUND";
                };
            };
        };
    };
    getAllMobilityTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": ("STATIC_STRETCHING" | "DYNAMIC_MOBILITY" | "FOAM_ROLLING" | "YOGA" | "PNF_STRETCHING" | "ACTIVE_STRETCHING" | "MOBILITY_DRILLS")[];
                };
            };
        };
    };
    getMobilityTypeByName: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": "STATIC_STRETCHING" | "DYNAMIC_MOBILITY" | "FOAM_ROLLING" | "YOGA" | "PNF_STRETCHING" | "ACTIVE_STRETCHING" | "MOBILITY_DRILLS";
                };
            };
        };
    };
    getAllJoints: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": ("NECK" | "SHOULDER" | "ELBOW" | "WRIST" | "THORACIC_SPINE" | "LUMBAR_SPINE" | "HIP" | "KNEE" | "ANKLE" | "FULL_BODY")[];
                };
            };
        };
    };
    getJointByName: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": "NECK" | "SHOULDER" | "ELBOW" | "WRIST" | "THORACIC_SPINE" | "LUMBAR_SPINE" | "HIP" | "KNEE" | "ANKLE" | "FULL_BODY";
                };
            };
        };
    };
    exerciseExists: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": boolean;
                };
            };
        };
    };
    getAllEquipment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": ("BODYWEIGHT" | "BARBELL" | "DUMBBELL" | "KETTLEBELL" | "WEIGHT_PLATE" | "EZ_BAR" | "TRAP_BAR" | "RESISTANCE_BAND" | "CABLE_MACHINE" | "SUSPENSION_TRAINER" | "SMITH_MACHINE" | "CHEST_PRESS" | "INCLINE_CHEST_PRESS" | "DECLINE_CHEST_PRESS" | "CHEST_FLY" | "CABLE_CROSSOVER" | "LAT_PULLDOWN" | "SEATED_CABLE_ROW" | "SEATED_ROW" | "T_BAR_ROW" | "BACK_EXTENSION" | "ASSISTED_PULL_UP" | "SHOULDER_PRESS" | "LATERAL_RAISE" | "REAR_DELT_FLY" | "SHRUG_MACHINE" | "BICEP_CURL" | "PREACHER_CURL" | "TRICEP_EXTENSION" | "TRICEP_PRESSDOWN" | "TRICEP_DIP" | "LEG_PRESS" | "HACK_SQUAT" | "LEG_EXTENSION" | "LEG_CURL" | "SEATED_LEG_CURL" | "LYING_LEG_CURL" | "HIP_ABDUCTOR" | "HIP_ADDUCTOR" | "GLUTE_KICKBACK" | "PENDULUM_SQUAT" | "STANDING_CALF_RAISE" | "SEATED_CALF_RAISE" | "LEG_PRESS_CALF_RAISE" | "AB_CRUNCH_MACHINE" | "TORSO_ROTATION" | "CAPTAIN_CHAIR" | "TREADMILL" | "STATIONARY_BIKE" | "ROWING_MACHINE" | "ELLIPTICAL" | "STAIR_CLIMBER" | "ASSAULT_BIKE" | "SKI_MACHINE" | "PULL_UP_BAR" | "DIP_STATION" | "BENCH" | "POWER_RACK" | "PLYO_BOX" | "TRX" | "MEDICINE_BALL" | "SLAM_BALL" | "FOAM_ROLLER" | "YOGA_MAT" | "AB_WHEEL" | "BATTLE_ROPE")[];
                };
            };
        };
    };
    getEquipmentByName: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": "BODYWEIGHT" | "BARBELL" | "DUMBBELL" | "KETTLEBELL" | "WEIGHT_PLATE" | "EZ_BAR" | "TRAP_BAR" | "RESISTANCE_BAND" | "CABLE_MACHINE" | "SUSPENSION_TRAINER" | "SMITH_MACHINE" | "CHEST_PRESS" | "INCLINE_CHEST_PRESS" | "DECLINE_CHEST_PRESS" | "CHEST_FLY" | "CABLE_CROSSOVER" | "LAT_PULLDOWN" | "SEATED_CABLE_ROW" | "SEATED_ROW" | "T_BAR_ROW" | "BACK_EXTENSION" | "ASSISTED_PULL_UP" | "SHOULDER_PRESS" | "LATERAL_RAISE" | "REAR_DELT_FLY" | "SHRUG_MACHINE" | "BICEP_CURL" | "PREACHER_CURL" | "TRICEP_EXTENSION" | "TRICEP_PRESSDOWN" | "TRICEP_DIP" | "LEG_PRESS" | "HACK_SQUAT" | "LEG_EXTENSION" | "LEG_CURL" | "SEATED_LEG_CURL" | "LYING_LEG_CURL" | "HIP_ABDUCTOR" | "HIP_ADDUCTOR" | "GLUTE_KICKBACK" | "PENDULUM_SQUAT" | "STANDING_CALF_RAISE" | "SEATED_CALF_RAISE" | "LEG_PRESS_CALF_RAISE" | "AB_CRUNCH_MACHINE" | "TORSO_ROTATION" | "CAPTAIN_CHAIR" | "TREADMILL" | "STATIONARY_BIKE" | "ROWING_MACHINE" | "ELLIPTICAL" | "STAIR_CLIMBER" | "ASSAULT_BIKE" | "SKI_MACHINE" | "PULL_UP_BAR" | "DIP_STATION" | "BENCH" | "POWER_RACK" | "PLYO_BOX" | "TRX" | "MEDICINE_BALL" | "SLAM_BALL" | "FOAM_ROLLER" | "YOGA_MAT" | "AB_WHEEL" | "BATTLE_ROPE";
                };
            };
        };
    };
    getAllEnduranceTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": ("AEROBIC" | "ANAEROBIC" | "HIIT" | "SIT" | "LISS" | "TEMPO" | "FARTLEK" | "STEADY_STATE")[];
                };
            };
        };
    };
    getEnduranceTypeByName: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": "AEROBIC" | "ANAEROBIC" | "HIIT" | "SIT" | "LISS" | "TEMPO" | "FARTLEK" | "STEADY_STATE";
                };
            };
        };
    };
    getPersonalRecords: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PersonalRecordResponse"][];
                };
            };
        };
    };
    getPersonalRecordsByExercise: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exerciseId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PersonalRecordResponse"];
                };
            };
        };
    };
    getMuscleVolume: {
        parameters: {
            query?: {
                startDate?: string;
                endDate?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WeeklyMuscleVolumeResponse"];
                };
            };
        };
    };
    calculateAcwr: {
        parameters: {
            query?: {
                targetDate?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AcwrResponse"];
                };
            };
        };
    };
    calculate1Rm: {
        parameters: {
            query: {
                weight: number;
                unit?: "KG" | "LBS";
                reps: number;
                formula?: "EPLEY" | "BRZYCKI" | "LOMBARDI" | "MAYHEW" | "OCONNER" | "WATHEN";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OneRepMaxResponse"];
                };
            };
        };
    };
}
